### ISSUE TITLE
No contact information on how to contribute

### ISSUE THREAD

**Issue by noloerino** [TheCyaniteProject/exit_code_dev#6]
Hello there! I have some amount of Python experience, and have been looking for a project to contribute to. Since you don't seem to have contact information listed for how to contribute (or maybe I'm just bad at finding things), I decided that the easiest thing to do would be to open an issue.

At any rate, I'd love to be of assistance. Let me know what I can do to help.

**Comment by TheCyaniteProject** [comment]
Sorry for the late reply. There has been a misunderstanding, and it is my fault. This thread is no longer active, but this project is far from dead. It was switched over to Java a while back and moved to https://github.com/TheCyaniteProject/exit_code_java. I apologize for the confusion, and I have updated the README.MD to reflect this information; something I should have done a long time ago.
